// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using call_data_microcervice.API;

#nullable disable

namespace call_data_microcervice.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260607194108_Added call datetime")]
    partial class Addedcalldatetime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("call_data_microcervice.DTO.CallDataEntity", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "call_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CallId"));

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "call_date");

                    b.Property<float>("CallSessionTime")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "call_session_time");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "client_id");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "operator_id");

                    b.HasKey("CallId");

                    b.ToTable("CallDataEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
