"""Create clients table

Revision ID: 26d68dc8073f
Revises: c5893b2268c9
Create Date: 2026-06-05 17:03:40.466278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d68dc8073f'
down_revision: Union[str, Sequence[str], None] = 'c5893b2268c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Surname', sa.String(), nullable=False),
    sa.Column('Balance', sa.Integer(), nullable=False),
    sa.Column('Online', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('Operators')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Operators',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Operator_is_busy', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('Operators_pkey'))
    )
    op.drop_table('Clients')
    # ### end Alembic commands ###
