"""Delete demo balance

Revision ID: 7863de44cf96
Revises: 26d68dc8073f
Create Date: 2026-06-07 10:12:31.902469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7863de44cf96'
down_revision: Union[str, Sequence[str], None] = '26d68dc8073f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'Balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients', sa.Column('Balance', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
