class FontContainer: #Контейнер шрифтов.
    INTER_REGULAR: str = "Inter 18pt"
    INTER_SEMIBOLD: str = "Inter 24pt SemiBold"
    INTER_BOLD: str = "Inter 28pt Black"

    _base_sizes = {
        "TITLE_LOADING": 30,
        "TITLE": 16,
        "VERSION_FONT": 16,

        "BUTTON_PARAMETERS": 30,
        "EXERCISE_BUTTON_PARAMETERS": 26,

        "MODAL_BUTTON": 24,
        "MODAL_MESSAGE": 20,
        "MODAL_INPUT": 16,
        "MODAL_TITLE": 32,

        "TITLE_FONT": 50,

        "SETTINGS_SLIDER_FONT": 20,
        "SETTINGS_DROPDOWN": 20,
        "SETTINGS_DROPDOWN_SELECTED": 24,
        "SETTINGS_SWITCH_FONT": 18,

        "HELP_TEXT": 30,
        "HELP_BUTTON": 24,

        "EXERCISE": 20,
        "EXERCISE_BUTTON_RESULT": 24,
        "EXERCISE_BUTTON_SHOOTING": 24,
        "EXERCISE_TITLE": 40,
        "EXERCISE_TARGET": 24,
        "EXERCISE_DESCRIPTION": 16,

        "SHOOTING_SETTINGS_INPUT": 20,
        "SHOOTING_SETTINGS_INPUT_VALUE": 32,
        "SHOOTING_SETTINGS_LABEL": 40,
        "SHOOTING_SETTINGS_DROPDOWN": 18,

        "SHOOTING_SHOOTER": 40,
        "SHOOTING_TOTAL": 24,
        "SHOOTING_BUTTON": 24,
        "SHOOTING_LABEL": 24,
        "SHOOTING_CELL": 24,
        "SHOOTING_TABLE_TITLE": 24,

        "TIMER": 230,

        "RESULT_LABEL": 18,
        "RESULT_BUTTON_HOVER": 20,
        "RESULT_TABLE": 25,
        "RESULT_BUTTON": 25,
        "RESULT_TABLE_HEADER": 20,
        "RESULT_TABLE_TITLE": 20,

        "LANGUAGE_DROPDOWN": 15
    }

    TITLE_LOADING = (INTER_REGULAR, _base_sizes["TITLE_LOADING"])
    TITLE = (INTER_SEMIBOLD, _base_sizes["TITLE"])
    VERSION_FONT = (INTER_SEMIBOLD, _base_sizes["VERSION_FONT"])

    BUTTON_PARAMETERS = (INTER_REGULAR, _base_sizes["BUTTON_PARAMETERS"])
    EXERCISE_BUTTON_PARAMETERS = (INTER_REGULAR, _base_sizes["EXERCISE_BUTTON_PARAMETERS"])

    MODAL_BUTTON = (INTER_SEMIBOLD, _base_sizes["MODAL_BUTTON"])
    MODAL_MESSAGE = (INTER_REGULAR, _base_sizes["MODAL_MESSAGE"])
    MODAL_INPUT = (INTER_REGULAR, _base_sizes["MODAL_INPUT"])
    MODAL_TITLE = (INTER_SEMIBOLD, _base_sizes["MODAL_TITLE"])

    TITLE_FONT = (INTER_SEMIBOLD, _base_sizes["TITLE_FONT"])

    SETTINGS_SLIDER_FONT = (INTER_SEMIBOLD, _base_sizes["SETTINGS_SLIDER_FONT"])
    SETTINGS_DROPDOWN = (INTER_SEMIBOLD, _base_sizes["SETTINGS_DROPDOWN"])
    SETTINGS_DROPDOWN_SELECTED = (INTER_BOLD, _base_sizes["SETTINGS_DROPDOWN_SELECTED"])
    SETTINGS_SWITCH_FONT = (INTER_SEMIBOLD, _base_sizes["SETTINGS_SWITCH_FONT"])

    HELP_TEXT = (INTER_REGULAR, _base_sizes["HELP_TEXT"])
    HELP_BUTTON = (INTER_SEMIBOLD, _base_sizes["HELP_BUTTON"])

    EXERCISE = (INTER_REGULAR, _base_sizes["EXERCISE"])
    EXERCISE_BUTTON_RESULT = (INTER_REGULAR, _base_sizes["EXERCISE_BUTTON_RESULT"])
    EXERCISE_BUTTON_SHOOTING = (INTER_SEMIBOLD, _base_sizes["EXERCISE_BUTTON_SHOOTING"])
    EXERCISE_TITLE = (INTER_SEMIBOLD, _base_sizes["EXERCISE_TITLE"])
    EXERCISE_TARGET = (INTER_REGULAR, _base_sizes["EXERCISE_TARGET"])
    EXERCISE_DESCRIPTION = (INTER_REGULAR, _base_sizes["EXERCISE_DESCRIPTION"])

    SHOOTING_SETTINGS_INPUT = (INTER_REGULAR, _base_sizes["SHOOTING_SETTINGS_INPUT"])
    SHOOTING_SETTINGS_INPUT_VALUE = (INTER_SEMIBOLD, _base_sizes["SHOOTING_SETTINGS_INPUT_VALUE"])
    SHOOTING_SETTINGS_LABEL = (INTER_SEMIBOLD, _base_sizes["SHOOTING_SETTINGS_LABEL"])
    SHOOTING_SETTINGS_DROPDOWN = (INTER_REGULAR, _base_sizes["SHOOTING_SETTINGS_DROPDOWN"])

    SHOOTING_SHOOTER = (INTER_SEMIBOLD, _base_sizes["SHOOTING_SHOOTER"])
    SHOOTING_TOTAL = (INTER_SEMIBOLD, _base_sizes["SHOOTING_TOTAL"])
    SHOOTING_BUTTON = (INTER_SEMIBOLD, _base_sizes["SHOOTING_BUTTON"])
    SHOOTING_LABEL = (INTER_REGULAR, _base_sizes["SHOOTING_LABEL"])
    SHOOTING_CELL = (INTER_SEMIBOLD, _base_sizes["SHOOTING_CELL"])
    SHOOTING_TABLE_TITLE = (INTER_SEMIBOLD, _base_sizes["SHOOTING_TABLE_TITLE"])

    TIMER = (INTER_BOLD, _base_sizes["TIMER"])

    RESULT_LABEL = (INTER_REGULAR, _base_sizes["RESULT_LABEL"])
    RESULT_BUTTON_HOVER = (INTER_SEMIBOLD, _base_sizes["RESULT_BUTTON_HOVER"])
    RESULT_TABLE = (INTER_SEMIBOLD, _base_sizes["RESULT_TABLE"])
    RESULT_BUTTON = (INTER_BOLD, _base_sizes["RESULT_BUTTON"])
    RESULT_TABLE_HEADER = (INTER_REGULAR, _base_sizes["RESULT_TABLE_HEADER"])
    RESULT_TABLE_TITLE = (INTER_SEMIBOLD, _base_sizes["RESULT_TABLE_TITLE"])

    LANGUAGE_DROPDOWN = (INTER_SEMIBOLD, _base_sizes["LANGUAGE_DROPDOWN"])



